// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TournamentAuction.Api.Data;

#nullable disable

namespace TournamentAuction.Api.Migrations
{
    [DbContext(typeof(TournamentAuctionDbContext))]
    [Migration("20261006055902_AddPlayerCardRatings")]
    partial class AddPlayerCardRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuctionLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuctionLotId");

                    b.HasIndex("UserId");

                    b.HasIndex("AuctionSessionId", "CreatedAtUtc");

                    b.HasIndex("TournamentId", "CreatedAtUtc");

                    b.ToTable("AuctionEvents");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuctionSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentBid")
                        .HasColumnType("bigint");

                    b.Property<int>("DrawPosition")
                        .HasColumnType("integer");

                    b.Property<long?>("FinalPrice")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LeadingTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevealedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinningTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeadingTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerSetId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinningTeamId");

                    b.HasIndex("AuctionSessionId", "Status");

                    b.HasIndex("AuctionSessionId", "PlayerId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("AuctionSessionId", "PlayerSetId", "DrawPosition");

                    b.ToTable("AuctionLots");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUnsoldRound")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLotId");

                    b.HasIndex("CurrentSetId");

                    b.HasIndex("TournamentId", "Status");

                    b.ToTable("AuctionSessions");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.BasePriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Amount")
                        .IsUnique();

                    b.ToTable("BasePriceTiers");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<long>("BasePrice")
                        .HasColumnType("bigint");

                    b.Property<string>("CardPosition")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Defending")
                        .HasColumnType("integer");

                    b.Property<int?>("Diving")
                        .HasColumnType("integer");

                    b.Property<int?>("Dribbling")
                        .HasColumnType("integer");

                    b.Property<int?>("Handling")
                        .HasColumnType("integer");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Kicking")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("Pace")
                        .HasColumnType("integer");

                    b.Property<int?>("Passing")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Physical")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Positioning")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousTeam")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("Reflexes")
                        .HasColumnType("integer");

                    b.Property<int?>("Shooting")
                        .HasColumnType("integer");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSetId");

                    b.HasIndex("TournamentId", "Name");

                    b.HasIndex("TournamentId", "PlayerSetId");

                    b.HasIndex("TournamentId", "Status");

                    b.ToTable("Players", t =>
                        {
                            t.HasCheckConstraint("CK_Players_CardRatings", "(\"Pace\" IS NULL OR \"Pace\" BETWEEN 1 AND 99) AND (\"Shooting\" IS NULL OR \"Shooting\" BETWEEN 1 AND 99) AND (\"Passing\" IS NULL OR \"Passing\" BETWEEN 1 AND 99) AND (\"Dribbling\" IS NULL OR \"Dribbling\" BETWEEN 1 AND 99) AND (\"Defending\" IS NULL OR \"Defending\" BETWEEN 1 AND 99) AND (\"Physical\" IS NULL OR \"Physical\" BETWEEN 1 AND 99) AND (\"Diving\" IS NULL OR \"Diving\" BETWEEN 1 AND 99) AND (\"Handling\" IS NULL OR \"Handling\" BETWEEN 1 AND 99) AND (\"Kicking\" IS NULL OR \"Kicking\" BETWEEN 1 AND 99) AND (\"Reflexes\" IS NULL OR \"Reflexes\" BETWEEN 1 AND 99) AND (\"Speed\" IS NULL OR \"Speed\" BETWEEN 1 AND 99) AND (\"Positioning\" IS NULL OR \"Positioning\" BETWEEN 1 AND 99)");
                        });
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.PlayerRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("CardPosition")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousTeam")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortBio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId", "Phone");

                    b.HasIndex("TournamentId", "Status");

                    b.ToTable("PlayerRegistrations");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.PlayerSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("PlayerSets");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.RegistrationForm", b =>
                {
                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ClosedManually")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ClosesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("OpensAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TournamentId");

                    b.ToTable("RegistrationForms");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InitialPurse")
                        .HasColumnType("bigint");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.HasIndex("TournamentId", "ShortName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TournamentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.TournamentMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentMembers");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.TournamentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("DefaultBidIncrement")
                        .HasColumnType("bigint");

                    b.Property<long>("DefaultStartingPurse")
                        .HasColumnType("bigint");

                    b.Property<int>("MaximumSquadSize")
                        .HasColumnType("integer");

                    b.Property<long>("MinimumAcquisitionPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("MinimumSquadSize")
                        .HasColumnType("integer");

                    b.Property<bool>("PublicLiveViewEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SellAllPlayers")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique();

                    b.ToTable("TournamentSettings");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionEvent", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.AuctionLot", "AuctionLot")
                        .WithMany()
                        .HasForeignKey("AuctionLotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TournamentAuction.Api.Domain.AuctionSession", "AuctionSession")
                        .WithMany("Events")
                        .HasForeignKey("AuctionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionLot");

                    b.Navigation("AuctionSession");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionLot", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.AuctionSession", "AuctionSession")
                        .WithMany("Lots")
                        .HasForeignKey("AuctionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.Team", "LeadingTeam")
                        .WithMany()
                        .HasForeignKey("LeadingTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TournamentAuction.Api.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.PlayerSet", "PlayerSet")
                        .WithMany()
                        .HasForeignKey("PlayerSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuctionSession");

                    b.Navigation("LeadingTeam");

                    b.Navigation("Player");

                    b.Navigation("PlayerSet");

                    b.Navigation("Tournament");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionSession", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.AuctionLot", "CurrentLot")
                        .WithMany()
                        .HasForeignKey("CurrentLotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TournamentAuction.Api.Domain.PlayerSet", "CurrentSet")
                        .WithMany()
                        .HasForeignKey("CurrentSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("AuctionSessions")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLot");

                    b.Navigation("CurrentSet");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.BasePriceTier", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("BasePriceTiers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Player", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.PlayerSet", "PlayerSet")
                        .WithMany("Players")
                        .HasForeignKey("PlayerSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerSet");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.PlayerRegistration", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.PlayerSet", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("PlayerSets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.RegistrationForm", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Team", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Tournament", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.TournamentMember", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithMany("Members")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentAuction.Api.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.TournamentSettings", b =>
                {
                    b.HasOne("TournamentAuction.Api.Domain.Tournament", "Tournament")
                        .WithOne("Settings")
                        .HasForeignKey("TournamentAuction.Api.Domain.TournamentSettings", "TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.AuctionSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.PlayerSet", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.Tournament", b =>
                {
                    b.Navigation("AuctionSessions");

                    b.Navigation("BasePriceTiers");

                    b.Navigation("Members");

                    b.Navigation("PlayerSets");

                    b.Navigation("Players");

                    b.Navigation("Settings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TournamentAuction.Api.Domain.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
